---
version: '2.0'
services:
  redis:
    image: 'redis:latest'
    expose:
      - port: 6379
        as: 6379
        proto: tcp
        to:
          - global: true
    env:
      - REDIS_PASSWORD=yourpasswordhere
      - REDIS_AOF_ENABLED=no
      - ALLOW_EMPTY_PASSWORD=no
  coingecko-prices:
    image: 'ghcr.io/charlesjudith/get-crypto-prices:0.0.2'
    expose:
      - port: 8000
        as: 80
        to:
          - global: true
    env:
      - REDIS_PORT=6379 
      - REDIS_HOST=REDIS_NP_SERVICE_HOST # Replace that value by the $REDIS_NP_SERVICE_HOST visible in shell mode
      - REDIS_DB=0
      - REDIS_PASSWORD=yourpasswordhere
profiles:
  compute:
    redis:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 200Mi
        storage:
          - size: 200Mb
    coingecko-prices:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 200Mi
        storage:
          - size: 200Mi
  placement:
    dcloud:
      pricing:
        redis:
          denom: uakt
          amount: 1000
        coingecko-prices:
          denom: uakt
          amount: 1000
deployment:
  redis:
    dcloud:
      profile: redis
      count: 1
  coingecko-prices:
    dcloud:
      profile: coingecko-prices
      count: 1
